# Generated by Django 4.2 on 2025-03-07 19:50

import Cars.models
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modified', models.DateField(auto_now=True, verbose_name='Atualizado')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('car_model', models.CharField(max_length=140, verbose_name='Modelo')),
                ('car_year', models.IntegerField(verbose_name='Ano')),
                ('car_plate', models.CharField(max_length=7, unique=True, verbose_name='Número da Placa')),
                ('car_daily_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor diário')),
                ('car_color', models.CharField(max_length=140, verbose_name='Cor')),
                ('car_image', stdimage.models.StdImageField(blank=True, force_min_size=False, upload_to=Cars.models.get_file_path, variations={'thumb': {'crop': True, 'height': 480, 'width': 420}}, verbose_name='Imagem')),
                ('car_status', models.BooleanField(default=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Carro',
                'verbose_name_plural': 'Carros',
            },
        ),
        migrations.CreateModel(
            name='CompanyPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modified', models.DateField(auto_now=True, verbose_name='Atualizado')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('rent_company_phone_one', models.CharField(max_length=15, verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'Telefone da Locadora',
                'verbose_name_plural': 'Telefones das Locadoras',
            },
        ),
        migrations.CreateModel(
            name='CompanyRentCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modified', models.DateField(auto_now=True, verbose_name='Atualizado')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('rent_company_name', models.CharField(max_length=140, verbose_name='Nome')),
                ('rent_company_street', models.CharField(max_length=200, verbose_name='Rua')),
                ('rent_company_number', models.IntegerField(verbose_name='Número')),
                ('rent_company_neighborhood', models.CharField(max_length=200, verbose_name='Bairro')),
                ('rent_company_cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
            ],
            options={
                'verbose_name': 'Locadora',
                'verbose_name_plural': 'Locadoras',
            },
        ),
        migrations.CreateModel(
            name='MakerCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modified', models.DateField(auto_now=True, verbose_name='Atualizado')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('car_maker', models.CharField(max_length=200, verbose_name='Fabricante')),
            ],
            options={
                'verbose_name': 'Fabricante',
                'verbose_name_plural': 'Fabricantes',
            },
        ),
        migrations.CreateModel(
            name='RentedCars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_use', models.IntegerField(blank=None, verbose_name='Quantidade de dias')),
                ('rent_date', models.DateTimeField(auto_now_add=True, verbose_name='Data do aluguel')),
                ('return_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de devolução')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cars.car', verbose_name='Carro Alugado')),
            ],
        ),
    ]
