# Generated by Django 4.2 on 2025-03-07 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentedcars',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='companyphone',
            name='rent_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cars.companyrentcar', verbose_name='Locadora - Contato'),
        ),
        migrations.AddField(
            model_name='car',
            name='car_maker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cars.makercar', verbose_name='Fabricante'),
        ),
        migrations.AddField(
            model_name='car',
            name='car_rent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cars.companyrentcar', verbose_name='Locadora'),
        ),
    ]
