# Generated by Django 4.2 on 2025-03-07 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyphone',
            old_name='rent_company_phone_one',
            new_name='rent_company_phone',
        ),
    ]
