# Generated by Django 4.2 on 2025-03-07 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0003_rename_rent_company_phone_one_companyphone_rent_company_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentedcars',
            options={'verbose_name': 'Tabela de carro alugado', 'verbose_name_plural': 'Tabelas de carros alugados'},
        ),
    ]
