# Generated by Django 4.2 on 2025-03-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0005_registerrentcaruser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentedcars',
            name='day_use',
        ),
        migrations.AlterField(
            model_name='rentedcars',
            name='rent_date',
            field=models.DateField(verbose_name='Data do aluguel'),
        ),
        migrations.AlterField(
            model_name='rentedcars',
            name='return_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de devolução'),
        ),
    ]
