# Generated by Django 4.2 on 2025-03-11 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0006_remove_rentedcars_day_use_alter_rentedcars_rent_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerrentcaruser',
            name='day_use',
        ),
    ]
