# Generated by Django 4.2 on 2025-03-11 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0007_remove_registerrentcaruser_day_use'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='car_rent',
        ),
        migrations.DeleteModel(
            name='CompanyPhone',
        ),
        migrations.DeleteModel(
            name='CompanyRentCar',
        ),
    ]
